### ISSUE TITLE
Allow the listening port to be configurable.

### ISSUE THREAD

**Issue by pillarsdotnet** [mrlesmithjr/ansible-rsyslog#6]
Currently, the rsyslog port is hard-coded via template to 514.  It should be configurable via role variables.

**Comment by mrlesmithjr** [comment]
Did you set the following to `true`? `rsyslog_config: false`

**Comment by pillarsdotnet** [comment]
I *do* want to configure rsyslog via this module, but I also want to set the port to something other than 514.  I'll submit a PR shortly.

**Comment by mrlesmithjr** [comment]
It is already available in the [defaults/main.yml](https://raw.githubusercontent.com/mrlesmithjr/ansible-rsyslog/master/defaults/main.yml) so maybe I am confused on the issue? :) But in order for it to set it to something other than 514 you have to set `rsyslog_config: true`.

**Comment by pillarsdotnet** [comment]
Sure enough is.  (scratches head)  Maybe I was looking at an old version?  Thanks and sorry for the trouble.

**Comment by mrlesmithjr** [comment]
No trouble at all man. I was just confused myself.
